### ISSUE TITLE
Extraction des comportements en marge

### ISSUE THREAD

**Issue by fschmitt7** [fschmitt7/NeoDetection#11]
- Réaliser l'algo qui extrait les n% d'observations qui peuvent être considérées comme des anomalies

**Comment by abotsi** [comment]
J'ai ajouté une fonction dans KMeansClusterer et la paramètre k dans le constructeur, il me semble que ça fonctionne bien. Reste plus qu'à lier cette fonctionnalité à l'interface (i.e. utiliser la valeur de n entrée par l'utilisateur, et afficher graphiquement les anomalies)
