### ISSUE TITLE
Interface de paramétrage

### ISSUE THREAD

**Issue by fschmitt7** [fschmitt7/NeoDetection#4]
- Choisir fichier
- Choisir paramètres k et n

**Comment by abotsi** [comment]
C'est bon, non ?

**Comment by fschmitt7** [comment]
Nan pas tout à fait. Les fichiers on va les mettre dans le projet peut etre. Et plutot afficher la liste des trucs disponibles. Enfin je sais pas.

**Comment by abotsi** [comment]
Bon, on peut presque fermer ce ticket aussi ! Il faut juste encore récupérer les infos du formulaire avec d'appliquer k-means
