### ISSUE TITLE
Affichage de résultats

### ISSUE THREAD

**Issue by fschmitt7** [fschmitt7/NeoDetection#5]
- afficher les résultats du clustering sous forme de graphe
- afficher les anomalies

**Comment by abotsi** [comment]
Bon, je vais tenter de faire un affichage tableau sans css pour commence, puis rajouter des trucs au fur et à mesure. En attendant, vous pouvez continuer de faire des affichages console pour bosser sur la partie algo

**Comment by fschmitt7** [comment]
Hmm, pas besoin de te faire chier à faire un affichage tableau, simplement récupérer les données sur l'autre page ca suffit

**Comment by abotsi** [comment]
Récupérer les données ok, mais comment on les affiche autrement ? On peut
difficilement faire un graphique sans savoir combien de champs on a
Le 10 avr. 2015 20:11, "Frédéric Schmitt" <notifications@github.com> a
écrit :

**Comment by fschmitt7** [comment]
Si tu as récupéré les données, c'est bon. Tu sais ce que t'as. Pas besoin de les afficher. D'ailleurs on ne veut pas afficher le tableau. On veut juste le graphique

**Comment by fschmitt7** [comment]
à ce propos : j'ai trouvé un truc vachement sympa pour faire un graphique en 3D ca s'appelle Highcharts, c'est beaucoup plus simple que D3JS, et puis faire un graphique en 3D avec D3JS c'est galère. Dans le sujet y'a marqué que si on veut utiliser qqch d'autre on peut ! Est-ce que ca vous va ?

**Comment by abotsi** [comment]
Ok, j'ai un peu regardé HighCharts et ça me parait vraiment pas mal, je suis partant !

**Comment by fschmitt7** [comment]
si tu regardes sur slack, tu peux voir ce que ca donne
