### ISSUE TITLE
Analyser le dataset

### ISSUE THREAD

**Issue by fschmitt7** [fschmitt7/NeoDetection#9]
Choisir les données à utiliser

**Comment by abotsi** [comment]
Je voulais justement le créer celui là ! 
Si on veut pas trop prendre de décision, on peut aussi coder un truc pour que l'utilisateur sélectionne led champs/colonnes sur lesquelles il veut faire la détection, vous en pensez quoi ?

**Comment by fschmitt7** [comment]
Si on a le temps, oui

**Comment by fschmitt7** [comment]
choisir 3 parmis count, srv_count, dst_host_count, dst_host_srv_count, ca parait pas mal
